import type { Metadata } from "next";
import { Sumana} from "next/font/google";
import "./globals.css";

const sumana = Sumana({weight:['400','700'],subsets:["devanagari"]});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sumana.className}  bg-white `}>{children}</body>
    </html>
  );
}
